.TH "kernel32/cpu.hpp" 3 "Sat Dec 5 2015" "kOdin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kernel32/cpu.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'types\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBkCpu\fP"
.br
.RI "\fIClass for CPU registers\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fB_kReadCPUID\fP (\fBDWORD\fP dwEAX, \fBDWORD\fP *pdwEAX, \fBDWORD\fP *pdwEBX, \fBDWORD\fP *pdwECX, \fBDWORD\fP *pdwEDX)"
.br
.ti -1c
.RI "void \fB_kSwitchAndExecute64bitsKernel\fP (void)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void _kReadCPUID (\fBDWORD\fPdwEAX, \fBDWORD\fP *pdwEAX, \fBDWORD\fP *pdwEBX, \fBDWORD\fP *pdwECX, \fBDWORD\fP *pdwEDX)"

.SS "void _kSwitchAndExecute64bitsKernel (void)"

.SH "Author"
.PP 
Generated automatically by Doxygen for kOdin from the source code\&.
