.TH "kCharactorStruct" 3 "Sat Dec 5 2015" "kOdin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kCharactorStruct \- 
.PP
Data structure for text to print in video mode\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <types\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBbCharactor\fP"
.br
.RI "\fICharactor\&. \fP"
.ti -1c
.RI "\fBBYTE\fP \fBbAttribute\fP"
.br
.RI "\fIAttribute\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Data structure for text to print in video mode\&. 
.PP
Definition at line 12 of file types\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBYTE\fP kCharactorStruct::bAttribute"

.PP
Attribute\&. 
.PP
Definition at line 14 of file types\&.hpp\&.
.SS "\fBBYTE\fP kCharactorStruct::bCharactor"

.PP
Charactor\&. 
.PP
Definition at line 13 of file types\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kOdin from the source code\&.
