.TH "kKeyMappingEntry" 3 "Sat Dec 5 2015" "kOdin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kKeyMappingEntry \- 
.PP
Struct for Scan Code Table\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <keyMappingEntry\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBBYTE\fP \fBbNormalCode\fP"
.br
.ti -1c
.RI "\fBBYTE\fP \fBbCombinedCode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct for Scan Code Table\&. 
.PP
Definition at line 58 of file keyMappingEntry\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBYTE\fP kKeyMappingEntry::bCombinedCode"

.PP
Definition at line 63 of file keyMappingEntry\&.hpp\&.
.SS "\fBBYTE\fP kKeyMappingEntry::bNormalCode"

.PP
Definition at line 60 of file keyMappingEntry\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kOdin from the source code\&.
