.TH "kMemory" 3 "Sat Dec 5 2015" "kOdin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kMemory \- 
.PP
Class for memory\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <memory\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBkIsMemoryEnough\fP (void)"
.br
.RI "\fICheck the size of memory is larget than the minimum\&. \fP"
.ti -1c
.RI "bool \fBkInitializeKernel64Area\fP (void)"
.br
.RI "\fIInitialize kernel area for IA-32e with 0\&. \fP"
.ti -1c
.RI "void \fBkInitializePageManager\fP (void)"
.br
.RI "\fIInitialize page manager\&. \fP"
.ti -1c
.RI "void \fBkCopyKernel64ImageTo2MB\fP (void)"
.br
.RI "\fICopy IA-32e mode kernel to 0x200000 (= 2 MB) \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBkPageManager\fP \fBclPM\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class for memory\&. 
.PP
Definition at line 6 of file memory\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void kMemory::kCopyKernel64ImageTo2MB (void)"

.PP
Copy IA-32e mode kernel to 0x200000 (= 2 MB) 
.PP
Definition at line 56 of file memory\&.cpp\&.
.SS "bool kMemory::kInitializeKernel64Area (void)"

.PP
Initialize kernel area for IA-32e with 0\&. 
.PP
Definition at line 4 of file memory\&.cpp\&.
.SS "void kMemory::kInitializePageManager (void)"

.PP
Initialize page manager\&. 
.PP
Definition at line 81 of file memory\&.cpp\&.
.SS "bool kMemory::kIsMemoryEnough (void)"

.PP
Check the size of memory is larget than the minimum\&. 
.PP
Definition at line 29 of file memory\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBkPageManager\fP kMemory::clPM\fC [private]\fP"

.PP
Definition at line 8 of file memory\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kOdin from the source code\&.
