.TH "kPageTableEntry" 3 "Sat Dec 5 2015" "kOdin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kPageTableEntry \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <page\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDWORD\fP \fBdwAttributeAndLowerBaseAddress\fP"
.br
.ti -1c
.RI "\fBDWORD\fP \fBdwUpperBaseAddressAndEXB\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 28 of file page\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBDWORD\fP kPageTableEntry::dwAttributeAndLowerBaseAddress"

.PP
Definition at line 37 of file page\&.hpp\&.
.SS "\fBDWORD\fP kPageTableEntry::dwUpperBaseAddressAndEXB"

.PP
Definition at line 43 of file page\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kOdin from the source code\&.
