.TH "kUtils" 3 "Sat Dec 5 2015" "kOdin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kUtils \- 
.PP
Class for Utilities\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <utils\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBkPrintString\fP (int iX, int iY, const char *pcString)"
.br
.RI "\fIPrint message\&. \fP"
.ti -1c
.RI "bool \fBkPrintString\fP (int iX, int iY, const char *pcString)"
.br
.ti -1c
.RI "void \fBkShell\fP (\fBkKeyboard\fP &clKeyboard, \fBDWORD\fP &dwline)"
.br
.RI "\fISimple shell\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Class for Utilities\&. 
.PP
Definition at line 6 of file utils\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool kUtils::kPrintString (intiX, intiY, const char *pcString)"

.PP
Print message\&. 
.PP
Definition at line 4 of file utils\&.cpp\&.
.SS "bool kUtils::kPrintString (intiX, intiY, const char *pcString)"

.SS "void kUtils::kShell (\fBkKeyboard\fP &clKeyboard, \fBDWORD\fP &dwline)"

.PP
Simple shell\&. 
.PP
Definition at line 18 of file utils\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for kOdin from the source code\&.
