.TH "kernel32/page.hpp" 3 "Sat Dec 5 2015" "kOdin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kernel32/page.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'types\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBkPageTableEntry\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPAGE_FLAGS_P\fP   0x00000001"
.br
.ti -1c
.RI "#define \fBPAGE_FLAGS_RW\fP   0x00000002"
.br
.ti -1c
.RI "#define \fBPAGE_FLAGS_US\fP   0x00000004"
.br
.ti -1c
.RI "#define \fBPAGE_FLAGS_PWT\fP   0x00000008"
.br
.ti -1c
.RI "#define \fBPAGE_FLAGS_PCD\fP   0x00000010"
.br
.ti -1c
.RI "#define \fBPAGE_FLAGS_A\fP   0x00000020"
.br
.ti -1c
.RI "#define \fBPAGE_FLAGS_D\fP   0x00000040"
.br
.ti -1c
.RI "#define \fBPAGE_FLAGS_PS\fP   0x00000080"
.br
.ti -1c
.RI "#define \fBPAGE_FLAGS_G\fP   0x00000100"
.br
.ti -1c
.RI "#define \fBPAGE_FLAGS_PAT\fP   0x00001000"
.br
.ti -1c
.RI "#define \fBPAGE_FLAGS_EXB\fP   0x80000000"
.br
.ti -1c
.RI "#define \fBPAGE_FLAGS_DEFAULT\fP   (\fBPAGE_FLAGS_P\fP || \fBPAGE_FLAGS_RW\fP)"
.br
.ti -1c
.RI "#define \fBPAGE_TABLESIZE\fP   0x1000"
.br
.ti -1c
.RI "#define \fBPAGE_MAXENTRYCOUNT\fP   512"
.br
.ti -1c
.RI "#define \fBPAGE_DEFAULTSIZE\fP   0x200000"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PAGE_DEFAULTSIZE   0x200000"

.PP
Definition at line 22 of file page\&.hpp\&.
.SS "#define PAGE_FLAGS_A   0x00000020"

.PP
Definition at line 11 of file page\&.hpp\&.
.SS "#define PAGE_FLAGS_D   0x00000040"

.PP
Definition at line 12 of file page\&.hpp\&.
.SS "#define PAGE_FLAGS_DEFAULT   (\fBPAGE_FLAGS_P\fP || \fBPAGE_FLAGS_RW\fP)"

.PP
Definition at line 19 of file page\&.hpp\&.
.SS "#define PAGE_FLAGS_EXB   0x80000000"

.PP
Definition at line 17 of file page\&.hpp\&.
.SS "#define PAGE_FLAGS_G   0x00000100"

.PP
Definition at line 14 of file page\&.hpp\&.
.SS "#define PAGE_FLAGS_P   0x00000001"

.PP
Definition at line 6 of file page\&.hpp\&.
.SS "#define PAGE_FLAGS_PAT   0x00001000"

.PP
Definition at line 15 of file page\&.hpp\&.
.SS "#define PAGE_FLAGS_PCD   0x00000010"

.PP
Definition at line 10 of file page\&.hpp\&.
.SS "#define PAGE_FLAGS_PS   0x00000080"

.PP
Definition at line 13 of file page\&.hpp\&.
.SS "#define PAGE_FLAGS_PWT   0x00000008"

.PP
Definition at line 9 of file page\&.hpp\&.
.SS "#define PAGE_FLAGS_RW   0x00000002"

.PP
Definition at line 7 of file page\&.hpp\&.
.SS "#define PAGE_FLAGS_US   0x00000004"

.PP
Definition at line 8 of file page\&.hpp\&.
.SS "#define PAGE_MAXENTRYCOUNT   512"

.PP
Definition at line 21 of file page\&.hpp\&.
.SS "#define PAGE_TABLESIZE   0x1000"

.PP
Definition at line 20 of file page\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for kOdin from the source code\&.
