.TH "kernel32/pageManager.hpp" 3 "Sat Dec 5 2015" "kOdin" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kernel32/pageManager.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'page\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBkPageManager\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for kOdin from the source code\&.
