var annotated =
[
    [ "kCharactorStruct", "d8/dbe/structk_charactor_struct.html", "d8/dbe/structk_charactor_struct" ],
    [ "kCpu", "d9/d0e/classk_cpu.html", "d9/d0e/classk_cpu" ],
    [ "kDT", "da/d13/classk_d_t.html", "da/d13/classk_d_t" ],
    [ "kDTRStruct", "d4/d6e/structk_d_t_r_struct.html", "d4/d6e/structk_d_t_r_struct" ],
    [ "kGDT", "d8/d83/classk_g_d_t.html", "d8/d83/classk_g_d_t" ],
    [ "kGDTEntry16Struct", "d3/dbc/structk_g_d_t_entry16_struct.html", "d3/dbc/structk_g_d_t_entry16_struct" ],
    [ "kGDTEntry8Struct", "d9/d8c/structk_g_d_t_entry8_struct.html", "d9/d8c/structk_g_d_t_entry8_struct" ],
    [ "kIDT", "d4/db2/classk_i_d_t.html", "d4/db2/classk_i_d_t" ],
    [ "kIDTEntryStruct", "dc/d68/structk_i_d_t_entry_struct.html", "dc/d68/structk_i_d_t_entry_struct" ],
    [ "kIH", "d6/d88/classk_i_h.html", "d6/d88/classk_i_h" ],
    [ "kKeyboard", "de/d2e/classk_keyboard.html", "de/d2e/classk_keyboard" ],
    [ "kKeyMappingEntry", "d5/d01/structk_key_mapping_entry.html", "d5/d01/structk_key_mapping_entry" ],
    [ "kKeyQueueDataStruct", "da/ddb/structk_key_queue_data_struct.html", "da/ddb/structk_key_queue_data_struct" ],
    [ "kMemory", "d6/d9c/classk_memory.html", "d6/d9c/classk_memory" ],
    [ "kPageManager", "d8/d6a/classk_page_manager.html", "d8/d6a/classk_page_manager" ],
    [ "kPageTableEntry", "d8/d9a/structk_page_table_entry.html", "d8/d9a/structk_page_table_entry" ],
    [ "kPIC", "d8/da9/classk_p_i_c.html", "d8/da9/classk_p_i_c" ],
    [ "kPort", "d9/d2f/classk_port.html", "d9/d2f/classk_port" ],
    [ "kQueue", "dd/dce/classk_queue.html", "dd/dce/classk_queue" ],
    [ "kShell", "de/dc1/classk_shell.html", "de/dc1/classk_shell" ],
    [ "kTSSStruct", "df/d1d/structk_t_s_s_struct.html", "df/d1d/structk_t_s_s_struct" ],
    [ "kUtils", "db/daa/classk_utils.html", "db/daa/classk_utils" ]
];