all: ImageMaker

ImageMaker:
	@echo
	@echo ===== imageMaker Build Start ====================================
	@echo
	
	make -C imageMaker
	
	@echo
	@echo ===== imageMaker Build Complete =================================
	@echo

clean:
	make -C imageMaker clean
